#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint

# Only run unit tests if you've edited the tested code (or the tests)
if git diff --name-only --cached | grep -E 'src\/|test\/|package\.json'; then
  npm run test
fi

# Only regenerate the report documentation if you've edited the reports (or the generation script)
if git diff --name-only --cached | grep -E 'src\/reports|scripts\/genReportDocs|package\.json'; then
  npm run genReportDocs
fi
